### ISSUE TITLE
Integrate binder

### ISSUE THREAD

**Issue by elbosso** [jerry-git/learn-python3#12]
Integrate Links for Binder https://mybinder.org/

either as 

https://mybinder.org/v2/gh/jerry-git/learn-python3/master

or as badge:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jerry-git/learn-python3/master)

**Comment by jerry-git** [comment]
Happy to take a PR for this 🙂

**Comment by jerry-git** [comment]
Added in https://github.com/jerry-git/learn-python3/pull/37. Kudos to @elbosso 🥇
