### ISSUE TITLE
ipytest.magic seems deprecated

### ISSUE THREAD

**Issue by Peer202** [jerry-git/learn-python3#32]
When doing the "testing with pytest part 1" notebook, there is an error, saying that a attribute called ipytest.magic doesnt exist. When having a look at the page for ipytest, i noticed that the usage seems to have changed. https://pypi.org/project/ipytest/
Did i understand that correctly? I installed ipytest for the first time today.

**Comment by jerry-git** [comment]
Indeed! Thanks for the report.

Fixed in https://github.com/jerry-git/learn-python3/pull/35
