### ISSUE TITLE
Add the logical ordering of Python Notesbooks

### ISSUE THREAD

**Issue by atingupta2005** [jerry-git/learn-python3#9]
When I cloned the repository on my local system, I am not able to follow the logical order of the notebooks. In other words on the Github Repository a logical order is specified against each topic as below:

1.	Strings [notebook] [exercise]
2.	Numbers [notebook] [exercise]
3.	Conditionals [notebook] [exercise]
4.	Lists [notebook] [exercise]
5.	Dictionaries [notebook] [exercise]
6.	For loops [notebook] [exercise]
7.	Functions [notebook] [exercise]
8.	Testing with pytest - part 1 [notebook] [exercise]
9.	Recap exercise 1 [exercise]
10.	File I\O [notebook] [exercise]
11.	Classes [notebook] [exercise]
12.	Exceptions [notebook] [exercise]
13.	Modules and packages [notebook]
14.	Debugging [notebook] [exercise]
15.	Goodies of the Standard Library - part 1 [notebook] [exercise]
16.	Testing with pytest - part 2 [notebook] [exercise]
17.	Virtual environment [notebook]
18.	Project structure [notebook]
19.	Recap exercise 2 [exercise]

But in the Cloned repository the files are in the albhatic order of the file name. There is no way to know in which order one should study. I think it will be better that we should put some index for these notebooks for easy navigation.

Also the same situation for HTML pages. There should be some logical order for those.

Thanks

**Comment by jerry-git** [comment]
Btw, in addition to the plain README file, you can use this https://jerry-git.github.io/learn-python3/ as index.

**Comment by jerry-git** [comment]
Added numbering also for the filenames in https://github.com/jerry-git/learn-python3/pull/35 🙂
